### ISSUE TITLE
Could not find package snap-static-pages in known packages

### ISSUE THREAD

**Issue by GildedHonour** [snapframework/snap-website#44]
An error in my haskell-snap-stack app:

```
build-depends:       base
                     , ghcv-snap
                     , snap
                     , snap-core
                     , snap-server
                     , heist
                     , snap-static-pages >= 1.0 && < 1.1
```

**Could not find package snap-static-pages in known packages
**

And the same thing for this:

```
build-depends:       base
                     , ghcv-snap
                     , snap
                     , snap-core
                     , snap-server
                     , heist
                     , snap-static-pages
```

**Comment by GildedHonour** [comment]
After cloning I can't install it either. Also, how can I it on hosting even if I install it locally?

**Comment by mightybyte** [comment]
Yeah, snap-static-pages was a quick and dirty library we threw together specifically for this website.  We didn't want to release it on hackage because it's not up to our normal quality standards.  To build snap-website you should get clone snap-static-pages from github here https://github.com/snapframework/snap-static-pages and add it as a source to your cabal sandbox.
